version: '3.7'

services:
  auth-db:
    image: postgres:15-bullseye
    container_name: auth-db
    environment:
      POSTGRES_PASSWORD: 'qwerty'
    ports:
      - "5434:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data

volumes:
  auth-db-data:

#cmds:
  #docker-compose up -d
  #docker-compose down
  #docker-compose logs -f user-db
  #docker-compose ps